[CmdletBinding()]
param(
    [string]$JoomlaBaseUrl,
    [string]$ApiToken,
    [string]$DocsRoot = (Join-Path $PSScriptRoot "Nodes"),
    [string]$TopCategoryTitle = "Genesis Nodes",
    [string]$TopCategoryAlias = "genesis-nodes",
    [string]$RemoteImageUrlBase = "/images/genesis-nodes",
    [string]$JoomlaImageRootPath,
    [string]$SourceUrlBase,
    [string]$Language = "*",
    [string]$CategoryPayloadJsonPath,
    [string]$ArticlePayloadJsonPath,
    [switch]$SkipImageCopy,
    [switch]$SkipArticleImport,
    [switch]$DryRun,
    [switch]$RelaunchedInPwsh
)

<#
.SYNOPSIS
Bulk-imports generated Genesis node documentation into Joomla.

.DESCRIPTION
This script imports the generated node pages under Documentation/Nodes/_nodes into
Joomla articles via Joomla's content API. It also supports mirroring node screenshot
files into a Joomla site's /images tree when that path is mounted locally.

The importer expects the documentation generated by:
    Documentation/Generate-GenesisNodeDocs.ps1

It performs the import in two passes:
1. Create or update categories and articles.
2. Patch article bodies again so any node-to-node markdown links can be rewritten
   using the real Joomla article IDs.

.EXAMPLE
pwsh ./Documentation/Import-JoomlaNodeDocs.ps1 `
  -JoomlaBaseUrl "https://example.com" `
  -ApiToken "YOUR_TOKEN" `
  -JoomlaImageRootPath "\\server\joomla\images\genesis-nodes"

.EXAMPLE
pwsh ./Documentation/Import-JoomlaNodeDocs.ps1 -DryRun -Verbose

.NOTES
- Joomla article import uses the content API under /api/index.php/v1/content/articles
- Category import uses the content API under /api/index.php/v1/content/categories
- If your Joomla site needs extra payload fields such as workflow configuration,
  pass them in via -CategoryPayloadJsonPath and/or -ArticlePayloadJsonPath
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Restart-InPwshIfNeeded {
    if ($PSVersionTable.PSVersion.Major -ge 7 -and (Get-Command ConvertFrom-Markdown -ErrorAction SilentlyContinue)) {
        return
    }

    if ($RelaunchedInPwsh) {
        throw "This script requires PowerShell 7+ with the Microsoft.PowerShell.Utility module available. The current shell still does not provide ConvertFrom-Markdown."
    }

    $pwsh = Get-Command pwsh -ErrorAction SilentlyContinue
    if ($null -eq $pwsh) {
        throw "This script requires PowerShell 7+. 'pwsh' was not found on PATH, and the current shell does not provide ConvertFrom-Markdown."
    }

    $forwardedArgs = New-Object System.Collections.Generic.List[string]
    $forwardedArgs.Add("-NoProfile")
    $forwardedArgs.Add("-ExecutionPolicy")
    $forwardedArgs.Add("Bypass")
    $forwardedArgs.Add("-File")
    $forwardedArgs.Add($PSCommandPath)

    foreach ($entry in $PSBoundParameters.GetEnumerator() | Sort-Object Key) {
        if ($entry.Key -eq "RelaunchedInPwsh") {
            continue
        }

        if ($entry.Value -is [switch]) {
            if ($entry.Value.IsPresent) {
                $forwardedArgs.Add("-$($entry.Key)")
            }
            continue
        }

        if ($null -ne $entry.Value) {
            $forwardedArgs.Add("-$($entry.Key)")
            $forwardedArgs.Add([string]$entry.Value)
        }
    }

    $forwardedArgs.Add("-RelaunchedInPwsh")
    Write-Host "Current shell does not support this importer. Restarting it with PowerShell 7 (`pwsh`)."
    & $pwsh.Source @forwardedArgs
    exit $LASTEXITCODE
}

function Test-MarkdownConversionSupport {
    return ($PSVersionTable.PSVersion.Major -ge 7 -and (Get-Command ConvertFrom-Markdown -ErrorAction SilentlyContinue))
}

Restart-InPwshIfNeeded

$nodesRoot = Join-Path $DocsRoot "_nodes"
$imagesRoot = Join-Path $DocsRoot "_images"
$script:categoryCache = @{}
$script:articleCacheByCategoryId = @{}
$script:siteBaseUrl = ""
$script:apiRoot = ""
$script:headers = @{}
$script:nextDryCategoryId = 900000
$script:nextDryArticleId = 800000
$script:categoryStats = [ordered]@{
    Created = 0
    Reused = 0
}
$script:articleStats = [ordered]@{
    Created = 0
    UpdatedExisting = 0
    LinkPatched = 0
}
$script:imageStats = [ordered]@{
    Copied = 0
    Skipped = 0
}

function Write-Step {
    param([string]$Message)

    Write-Host $Message
}

function Normalize-SiteBaseUrl {
    param([string]$Url)

    if ([string]::IsNullOrWhiteSpace($Url)) {
        return ""
    }

    $normalized = $Url.Trim()
    $normalized = $normalized.TrimEnd("/")
    $normalized = [regex]::Replace($normalized, "/api/index\.php/v1/?$", "", [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    return $normalized.TrimEnd("/")
}

function Join-UrlPath {
    param(
        [string]$Base,
        [string]$Relative
    )

    $cleanRelative = ($Relative -replace "\\", "/").TrimStart("/")

    if ([string]::IsNullOrWhiteSpace($Base)) {
        return "/" + $cleanRelative
    }

    return $Base.TrimEnd("/") + "/" + $cleanRelative
}

function Get-RelativePath {
    param(
        [string]$BasePath,
        [string]$TargetPath
    )

    $baseFullPath = [IO.Path]::GetFullPath($BasePath)
    if (-not $baseFullPath.EndsWith([IO.Path]::DirectorySeparatorChar)) {
        $baseFullPath += [IO.Path]::DirectorySeparatorChar
    }

    $targetFullPath = [IO.Path]::GetFullPath($TargetPath)
    $baseUri = [Uri]$baseFullPath
    $targetUri = [Uri]$targetFullPath
    return [Uri]::UnescapeDataString($baseUri.MakeRelativeUri($targetUri).ToString()).Replace("\", "/")
}

function Get-ObjectPropertyValue {
    param(
        [object]$Object,
        [string]$Name,
        $Default = $null
    )

    if ($null -eq $Object) {
        return $Default
    }

    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) {
        return $Default
    }

    return $property.Value
}

function Get-JoomlaItems {
    param([object]$Response)

    if ($null -eq $Response) {
        return @()
    }

    $data = Get-ObjectPropertyValue -Object $Response -Name "data"
    if ($null -eq $data) {
        return @($Response)
    }

    if ($data -is [System.Array]) {
        return @($data)
    }

    return @($data)
}

function New-CategoryLookupKey {
    param(
        [string]$ParentId,
        [string]$Alias
    )

    return ("{0}|{1}" -f $ParentId, $Alias).ToLowerInvariant()
}

function Read-OptionalJsonHashtable {
    param([string]$Path)

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return @{}
    }

    if (-not (Test-Path $Path)) {
        throw "JSON payload override file not found: $Path"
    }

    return (Get-Content -Raw -Path $Path | ConvertFrom-Json -AsHashtable)
}

function Merge-Hashtables {
    param(
        [hashtable]$Base,
        [hashtable]$Override
    )

    $result = @{}

    foreach ($entry in $Base.GetEnumerator()) {
        $result[$entry.Key] = $entry.Value
    }

    foreach ($entry in $Override.GetEnumerator()) {
        if ($result.ContainsKey($entry.Key) -and
            $result[$entry.Key] -is [hashtable] -and
            $entry.Value -is [hashtable]) {
            $result[$entry.Key] = Merge-Hashtables -Base $result[$entry.Key] -Override $entry.Value
        }
        else {
            $result[$entry.Key] = $entry.Value
        }
    }

    return $result
}

function Invoke-JoomlaApi {
    param(
        [ValidateSet("GET", "POST", "PATCH")]
        [string]$Method,
        [string]$Path,
        [object]$Body
    )

    if ($DryRun) {
        throw "Invoke-JoomlaApi should not be called during dry runs."
    }

    $uri = Join-UrlPath -Base $script:apiRoot -Relative $Path
    $invokeArgs = @{
        Uri = $uri
        Method = $Method
        Headers = $script:headers
        TimeoutSec = 120
    }

    if ($PSBoundParameters.ContainsKey("Body") -and $null -ne $Body) {
        $invokeArgs.Body = ($Body | ConvertTo-Json -Depth 25 -Compress)
    }

    try {
        return Invoke-RestMethod @invokeArgs
    }
    catch {
        $details = if (-not [string]::IsNullOrWhiteSpace($_.ErrorDetails.Message)) {
            $_.ErrorDetails.Message
        }
        else {
            $_.Exception.Message
        }

        throw "Joomla API $Method $uri failed: $details"
    }
}

function Refresh-CategoryCache {
    if ($DryRun) {
        return
    }

    $script:categoryCache = @{}
    $response = Invoke-JoomlaApi -Method GET -Path "content/categories?page%5Blimit%5D=1000"

    foreach ($item in (Get-JoomlaItems $response)) {
        $attributes = Get-ObjectPropertyValue -Object $item -Name "attributes" -Default $item
        $alias = [string](Get-ObjectPropertyValue -Object $attributes -Name "alias" -Default "")
        $parentId = [string](Get-ObjectPropertyValue -Object $attributes -Name "parent_id" -Default (Get-ObjectPropertyValue -Object $attributes -Name "parentId" -Default ""))

        if ([string]::IsNullOrWhiteSpace($alias) -or [string]::IsNullOrWhiteSpace($parentId)) {
            continue
        }

        $key = New-CategoryLookupKey -ParentId $parentId -Alias $alias
        $script:categoryCache[$key] = [pscustomobject]@{
            Id = [string](Get-ObjectPropertyValue -Object $item -Name "id" -Default "")
            Alias = $alias
            Title = [string](Get-ObjectPropertyValue -Object $attributes -Name "title" -Default "")
            ParentId = $parentId
        }
    }
}

function Get-ArticlesForCategory {
    param([string]$CategoryId)

    if ($script:articleCacheByCategoryId.ContainsKey($CategoryId)) {
        return $script:articleCacheByCategoryId[$CategoryId]
    }

    if ($DryRun) {
        $script:articleCacheByCategoryId[$CategoryId] = @{}
        return $script:articleCacheByCategoryId[$CategoryId]
    }

    $path = "content/articles?filter%5Bcategory%5D=$CategoryId&page%5Blimit%5D=1000"
    $response = Invoke-JoomlaApi -Method GET -Path $path
    $lookup = @{}

    foreach ($item in (Get-JoomlaItems $response)) {
        $attributes = Get-ObjectPropertyValue -Object $item -Name "attributes" -Default $item
        $alias = [string](Get-ObjectPropertyValue -Object $attributes -Name "alias" -Default "")

        if ([string]::IsNullOrWhiteSpace($alias)) {
            continue
        }

        $lookup[$alias.ToLowerInvariant()] = [pscustomobject]@{
            Id = [string](Get-ObjectPropertyValue -Object $item -Name "id" -Default "")
            Alias = $alias
            Title = [string](Get-ObjectPropertyValue -Object $attributes -Name "title" -Default "")
            CategoryId = $CategoryId
        }
    }

    $script:articleCacheByCategoryId[$CategoryId] = $lookup
    return $lookup
}

function Get-TopLevelCategoryTitleMap {
    $map = @{}
    $categoryPages = Get-ChildItem -Path $DocsRoot -File -Filter *.md |
        Where-Object { $_.BaseName -ne "README" -and -not $_.BaseName.StartsWith("_") }

    foreach ($page in $categoryPages) {
        $firstLine = Get-Content -Path $page.FullName -TotalCount 1
        if ($firstLine -match '^#\s+Genesis Nodes:\s+(.+)$') {
            $map[$page.BaseName.ToLowerInvariant()] = $Matches[1].Trim()
        }
    }

    return $map
}

function Format-TitleFromSlug {
    param([string]$Slug)

    $textInfo = [System.Globalization.CultureInfo]::InvariantCulture.TextInfo
    $parts = $Slug -split "-"
    $words = foreach ($part in $parts) {
        if ($part -match '^\d') {
            $part.ToUpperInvariant()
        }
        else {
            $textInfo.ToTitleCase($part)
        }
    }

    return ($words -join " ").Trim()
}

function Get-CategoryDefinitions {
    $topLevelTitleMap = Get-TopLevelCategoryTitleMap
    $definitions = New-Object System.Collections.Generic.List[object]

    foreach ($directory in (Get-ChildItem -Path $nodesRoot -Directory -Recurse | Sort-Object FullName)) {
        $relativePath = Get-RelativePath -BasePath $nodesRoot -TargetPath $directory.FullName
        $segments = $relativePath -split "/"
        $alias = $segments[$segments.Count - 1]
        $parentRelativePath = if ($segments.Count -gt 1) { (($segments | Select-Object -SkipLast 1) -join "/") } else { "" }
        $title = if ($segments.Count -eq 1 -and $topLevelTitleMap.ContainsKey($alias.ToLowerInvariant())) {
            $topLevelTitleMap[$alias.ToLowerInvariant()]
        }
        else {
            Format-TitleFromSlug -Slug $alias
        }

        $definitions.Add([pscustomobject]@{
            RelativePath = $relativePath
            ParentRelativePath = $parentRelativePath
            Alias = $alias
            Title = $title
            Depth = $segments.Count
        })
    }

    return [object[]]($definitions | Sort-Object Depth, RelativePath)
}

function Get-FirstHeading {
    param([string]$Markdown)

    foreach ($line in ($Markdown -split "`r?`n")) {
        if ($line -match '^#\s+(.+)$') {
            return $Matches[1].Trim()
        }
    }

    return $null
}

function Get-ArticleDefinitions {
    $definitions = New-Object System.Collections.Generic.List[object]
    $files = Get-ChildItem -Path $nodesRoot -Recurse -File -Filter *.md | Sort-Object FullName

    foreach ($file in $files) {
        $relativePath = Get-RelativePath -BasePath $nodesRoot -TargetPath $file.FullName
        $categoryRelativePath = Split-Path -Path $relativePath -Parent
        $markdown = Get-Content -Raw -Path $file.FullName
        $title = Get-FirstHeading -Markdown $markdown

        if ([string]::IsNullOrWhiteSpace($title)) {
            $title = Format-TitleFromSlug -Slug $file.BaseName
        }

        $definitions.Add([pscustomobject]@{
            FilePath = $file.FullName
            RelativePath = $relativePath
            CategoryRelativePath = ($categoryRelativePath -replace "\\", "/")
            Alias = $file.BaseName
            Title = $title
            Markdown = $markdown
        })
    }

    return [object[]]$definitions
}

function Remove-GeneratedPreamble {
    param([string]$Markdown)

    $lines = $Markdown -split "`r?`n"
    $filtered = New-Object System.Collections.Generic.List[string]
    $removedTitle = $false

    foreach ($line in $lines) {
        if (-not $removedTitle -and $line -match '^#\s+') {
            $removedTitle = $true
            continue
        }

        if ($line -match '^>\s+This file is auto-generated') {
            continue
        }

        if ($line -match '^\[Back to index\]\(.+\)\s*\|\s*\[Back to .+\]\(.+\)\s*$') {
            continue
        }

        $filtered.Add($line)
    }

    return (($filtered -join "`n").Trim())
}

function Convert-NodeMarkdownToHtml {
    param(
        [psobject]$Article,
        [hashtable]$ArticleUrlMap
    )

    $markdown = Remove-GeneratedPreamble -Markdown $Article.Markdown

    $markdown = [regex]::Replace($markdown, '!\[(?<alt>[^\]]*)\]\((?<target>(?:\.\./)+_images/(?<path>[^)]+))\)', {
        param($match)

        $alt = $match.Groups["alt"].Value
        $relativeImagePath = $match.Groups["path"].Value.Replace("\", "/")
        $remoteUrl = Join-UrlPath -Base $RemoteImageUrlBase -Relative $relativeImagePath
        return "![{0}]({1})" -f $alt, $remoteUrl
    })

    $markdown = [regex]::Replace($markdown, '\[(?<label>[^\]]+)\]\((?<target>(?:\.\./)+Runtime/[^)]+)\)', {
        param($match)

        $label = $match.Groups["label"].Value
        $relativeRuntimePath = ($match.Groups["target"].Value -replace '^(?:\.\./)+', '').Replace("\", "/")

        if (-not [string]::IsNullOrWhiteSpace($SourceUrlBase)) {
            $sourceUrl = Join-UrlPath -Base $SourceUrlBase -Relative $relativeRuntimePath
            return "[{0}]({1})" -f $label, $sourceUrl
        }

        return "``{0}``" -f $label
    })

    $markdown = [regex]::Replace($markdown, '\[(?<label>[^\]]+)\]\((?<target>(?:\.\./)+_nodes/(?<path>[^)]+\.md))\)', {
        param($match)

        $label = $match.Groups["label"].Value
        $relativeArticlePath = $match.Groups["path"].Value.Replace("\", "/").ToLowerInvariant()

        if ($null -ne $ArticleUrlMap -and $ArticleUrlMap.ContainsKey($relativeArticlePath)) {
            return "[{0}]({1})" -f $label, $ArticleUrlMap[$relativeArticlePath]
        }

        return $label
    })

    $converted = ConvertFrom-Markdown -InputObject $markdown
    return $converted.Html.Trim()
}

function Build-ArticleUrl {
    param(
        [string]$ArticleId,
        [string]$CategoryId
    )

    $relativeUrl = "index.php?option=com_content&view=article&id=$ArticleId&catid=$CategoryId"
    return Join-UrlPath -Base $script:siteBaseUrl -Relative $relativeUrl
}

function Ensure-Category {
    param(
        [string]$Title,
        [string]$Alias,
        [string]$ParentId,
        [hashtable]$PayloadOverrides
    )

    $key = New-CategoryLookupKey -ParentId $ParentId -Alias $Alias

    if ($script:categoryCache.ContainsKey($key)) {
        $script:categoryStats.Reused++
        return $script:categoryCache[$key]
    }

    if ($DryRun) {
        $script:nextDryCategoryId++
        $category = [pscustomobject]@{
            Id = [string]$script:nextDryCategoryId
            Alias = $Alias
            Title = $Title
            ParentId = $ParentId
        }
        $script:categoryCache[$key] = $category
        $script:categoryStats.Created++
        return $category
    }

    $payload = @{
        title = $Title
        alias = $Alias
        extension = "com_content"
        parent_id = [int]$ParentId
        language = $Language
        published = 1
    }

    $payload = Merge-Hashtables -Base $payload -Override $PayloadOverrides
    $response = Invoke-JoomlaApi -Method POST -Path "content/categories" -Body $payload
    $createdItem = (Get-JoomlaItems $response | Select-Object -First 1)
    $createdAttributes = Get-ObjectPropertyValue -Object $createdItem -Name "attributes" -Default $createdItem

    $category = [pscustomobject]@{
        Id = [string](Get-ObjectPropertyValue -Object $createdItem -Name "id" -Default "")
        Alias = [string](Get-ObjectPropertyValue -Object $createdAttributes -Name "alias" -Default $Alias)
        Title = [string](Get-ObjectPropertyValue -Object $createdAttributes -Name "title" -Default $Title)
        ParentId = $ParentId
    }

    if ([string]::IsNullOrWhiteSpace($category.Id)) {
        throw "Category creation succeeded but Joomla did not return a category id for '$Title'."
    }

    $script:categoryCache[$key] = $category
    $script:categoryStats.Created++
    return $category
}

function Ensure-Article {
    param(
        [psobject]$Article,
        [string]$CategoryId,
        [string]$Html,
        [hashtable]$PayloadOverrides,
        [switch]$LinkPatch
    )

    $articleLookup = Get-ArticlesForCategory -CategoryId $CategoryId
    $lookupKey = $Article.Alias.ToLowerInvariant()

    if ($articleLookup.ContainsKey($lookupKey)) {
        $existing = $articleLookup[$lookupKey]

        if ($DryRun) {
            if ($LinkPatch) {
                $script:articleStats.LinkPatched++
            }
            else {
                $script:articleStats.UpdatedExisting++
            }
            return $existing
        }

        $payload = @{
            id = [int]$existing.Id
            title = $Article.Title
            alias = $Article.Alias
            catid = [int]$CategoryId
            introtext = $Html
            fulltext = ""
            language = $Language
            metadesc = ""
            metakey = ""
        }

        $payload = Merge-Hashtables -Base $payload -Override $PayloadOverrides
        Invoke-JoomlaApi -Method PATCH -Path ("content/articles/{0}" -f $existing.Id) -Body $payload | Out-Null
        if ($LinkPatch) {
            $script:articleStats.LinkPatched++
        }
        else {
            $script:articleStats.UpdatedExisting++
        }
        return $existing
    }

    if ($DryRun) {
        $script:nextDryArticleId++
        $created = [pscustomobject]@{
            Id = [string]$script:nextDryArticleId
            Alias = $Article.Alias
            Title = $Article.Title
            CategoryId = $CategoryId
        }
        $articleLookup[$lookupKey] = $created
        $script:articleStats.Created++
        return $created
    }

    $payload = @{
        title = $Article.Title
        alias = $Article.Alias
        articletext = $Html
        catid = [int]$CategoryId
        language = $Language
        metadesc = ""
        metakey = ""
    }

    $payload = Merge-Hashtables -Base $payload -Override $PayloadOverrides
    $response = Invoke-JoomlaApi -Method POST -Path "content/articles" -Body $payload
    $createdItem = (Get-JoomlaItems $response | Select-Object -First 1)
    $createdAttributes = Get-ObjectPropertyValue -Object $createdItem -Name "attributes" -Default $createdItem

    $created = [pscustomobject]@{
        Id = [string](Get-ObjectPropertyValue -Object $createdItem -Name "id" -Default "")
        Alias = [string](Get-ObjectPropertyValue -Object $createdAttributes -Name "alias" -Default $Article.Alias)
        Title = [string](Get-ObjectPropertyValue -Object $createdAttributes -Name "title" -Default $Article.Title)
        CategoryId = $CategoryId
    }

    if ([string]::IsNullOrWhiteSpace($created.Id)) {
        throw "Article creation succeeded but Joomla did not return an article id for '$($Article.Title)'."
    }

    $articleLookup[$lookupKey] = $created
    $script:articleStats.Created++
    return $created
}

function Copy-ImagesToJoomlaRoot {
    param([string]$DestinationRoot)

    $actualImages = @()
    if (Test-Path $imagesRoot) {
        $actualImages = Get-ChildItem -Path $imagesRoot -Recurse -File |
            Where-Object { $_.Extension -ne ".meta" }
    }

    if ($actualImages.Count -eq 0) {
        Write-Step "No screenshot files were found under $imagesRoot. Skipping image copy."
        return
    }

    if ([string]::IsNullOrWhiteSpace($DestinationRoot)) {
        Write-Step "Image copy skipped because -JoomlaImageRootPath was not provided."
        $script:imageStats.Skipped += $actualImages.Count
        return
    }

    foreach ($image in $actualImages) {
        $relativePath = Get-RelativePath -BasePath $imagesRoot -TargetPath $image.FullName
        $targetPath = Join-Path $DestinationRoot ($relativePath -replace "/", "\")
        $targetDirectory = Split-Path -Parent $targetPath

        if ($DryRun) {
            $script:imageStats.Copied++
            continue
        }

        if (-not (Test-Path $targetDirectory)) {
            New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
        }

        Copy-Item -Path $image.FullName -Destination $targetPath -Force
        $script:imageStats.Copied++
    }
}

if (-not (Test-Path $DocsRoot)) {
    throw "Documentation root not found: $DocsRoot"
}

if (-not (Test-Path $nodesRoot)) {
    throw "Node markdown directory not found: $nodesRoot"
}

if (-not (Get-Command ConvertFrom-Markdown -ErrorAction SilentlyContinue)) {
    throw "ConvertFrom-Markdown is required but is not available in this PowerShell installation."
}

$script:siteBaseUrl = Normalize-SiteBaseUrl -Url $JoomlaBaseUrl
$script:apiRoot = if ([string]::IsNullOrWhiteSpace($script:siteBaseUrl)) {
    ""
}
else {
    Join-UrlPath -Base $script:siteBaseUrl -Relative "api/index.php/v1"
}

if (-not $DryRun) {
    if ([string]::IsNullOrWhiteSpace($script:siteBaseUrl)) {
        throw "-JoomlaBaseUrl is required unless -DryRun is used."
    }

    if ([string]::IsNullOrWhiteSpace($ApiToken)) {
        throw "-ApiToken is required unless -DryRun is used."
    }

    $script:headers = @{
        "Accept" = "application/vnd.api+json"
        "Content-Type" = "application/json"
        "X-Joomla-Token" = $ApiToken.Trim()
    }
}

$categoryPayloadOverrides = Read-OptionalJsonHashtable -Path $CategoryPayloadJsonPath
$articlePayloadOverrides = Read-OptionalJsonHashtable -Path $ArticlePayloadJsonPath
$categoryDefinitions = Get-CategoryDefinitions
$articleDefinitions = Get-ArticleDefinitions
$categoryIdByRelativePath = @{}
$articleInfoByRelativePath = @{}
$articleUrlMap = @{}

Write-Step ("Discovered {0} category folders and {1} node pages under {2}." -f $categoryDefinitions.Count, $articleDefinitions.Count, $DocsRoot)

if (-not $SkipImageCopy) {
    Copy-ImagesToJoomlaRoot -DestinationRoot $JoomlaImageRootPath
}
else {
    Write-Step "Image copy skipped by request."
}

if (-not $SkipArticleImport) {
    if (-not $DryRun) {
        Refresh-CategoryCache
    }

    $topCategory = Ensure-Category -Title $TopCategoryTitle -Alias $TopCategoryAlias -ParentId "1" -PayloadOverrides $categoryPayloadOverrides
    $categoryIdByRelativePath[""] = $topCategory.Id

    foreach ($category in $categoryDefinitions) {
        $parentCategoryId = $categoryIdByRelativePath[$category.ParentRelativePath]
        $ensuredCategory = Ensure-Category `
            -Title $category.Title `
            -Alias $category.Alias `
            -ParentId $parentCategoryId `
            -PayloadOverrides $categoryPayloadOverrides

        $categoryIdByRelativePath[$category.RelativePath] = $ensuredCategory.Id
    }

    Write-Step ("Resolved {0} Joomla categories." -f ($categoryIdByRelativePath.Keys.Count - 1))

    for ($index = 0; $index -lt $articleDefinitions.Count; $index++) {
        $article = $articleDefinitions[$index]
        $categoryId = $categoryIdByRelativePath[$article.CategoryRelativePath]
        $html = Convert-NodeMarkdownToHtml -Article $article -ArticleUrlMap @{}

        Write-Progress -Activity "Importing Joomla articles" -Status $article.Title -PercentComplete ((($index + 1) / [math]::Max(1, $articleDefinitions.Count)) * 100)

        $articleInfo = Ensure-Article `
            -Article $article `
            -CategoryId $categoryId `
            -Html $html `
            -PayloadOverrides $articlePayloadOverrides

        $articleInfoByRelativePath[$article.RelativePath.ToLowerInvariant()] = [pscustomobject]@{
            Id = $articleInfo.Id
            Alias = $article.Alias
            Title = $article.Title
            CategoryId = $categoryId
        }
    }

    Write-Progress -Activity "Importing Joomla articles" -Completed

    foreach ($relativePath in $articleInfoByRelativePath.Keys) {
        $info = $articleInfoByRelativePath[$relativePath]
        $articleUrlMap[$relativePath] = Build-ArticleUrl -ArticleId $info.Id -CategoryId $info.CategoryId
    }

    for ($index = 0; $index -lt $articleDefinitions.Count; $index++) {
        $article = $articleDefinitions[$index]
        $categoryId = $categoryIdByRelativePath[$article.CategoryRelativePath]
        $html = Convert-NodeMarkdownToHtml -Article $article -ArticleUrlMap $articleUrlMap

        Write-Progress -Activity "Patching Joomla article links" -Status $article.Title -PercentComplete ((($index + 1) / [math]::Max(1, $articleDefinitions.Count)) * 100)

        Ensure-Article `
            -Article $article `
            -CategoryId $categoryId `
            -Html $html `
            -PayloadOverrides $articlePayloadOverrides `
            -LinkPatch | Out-Null
    }

    Write-Progress -Activity "Patching Joomla article links" -Completed
}
else {
    Write-Step "Article import skipped by request."
}

Write-Step ""
Write-Step "Import summary"
Write-Step ("- Categories created: {0}" -f $script:categoryStats.Created)
Write-Step ("- Categories reused: {0}" -f $script:categoryStats.Reused)
Write-Step ("- Articles created: {0}" -f $script:articleStats.Created)
Write-Step ("- Existing articles updated: {0}" -f $script:articleStats.UpdatedExisting)
Write-Step ("- Articles link-patched: {0}" -f $script:articleStats.LinkPatched)
Write-Step ("- Images copied: {0}" -f $script:imageStats.Copied)
Write-Step ("- Images skipped: {0}" -f $script:imageStats.Skipped)

if ($DryRun) {
    Write-Step ""
    Write-Step "Dry run complete. No Joomla API calls or file copies were performed."
}
